jdbc:
  url: "jdbc:mysql://localhost:3306/announcements?useSSL=false"
  user: "user"
  passwd: "godbless123!"
  driver: "com.mysql.cj.jdbc.Driver"
  poolSize: 10
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring:
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

